apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: starlight-production-ingress
  namespace: starlight-production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "21m"
spec:
  ingressClassName: nginx
  rules:
    - host: prd.starlight-official.co.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: starlight-production-service
                port:
                  number: 80
